apiVersion: v1
kind: Service
metadata:
    name: rishiprakashtypescriptappazureci
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
      targetPort: 3000
    selector:
        app: rishiprakashtypescriptappazureci